### ISSUE TITLE
when i use python setup.py build develop

### ISSUE THREAD

**Issue by FlyingDita** [zillur-av/LVLane#11]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12'
/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running build
running build_py
copying lanedet/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet
copying lanedet/datasets/registry.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets
copying lanedet/datasets/base_dataset.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets
copying lanedet/datasets/culane.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets
copying lanedet/datasets/tusimple.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets
copying lanedet/datasets/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets
copying lanedet/engine/registry.py -> build/lib.linux-x86_64-cpython-38/lanedet/engine
copying lanedet/engine/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/engine
copying lanedet/engine/scheduler.py -> build/lib.linux-x86_64-cpython-38/lanedet/engine
copying lanedet/engine/optimizer.py -> build/lib.linux-x86_64-cpython-38/lanedet/engine
copying lanedet/engine/runner.py -> build/lib.linux-x86_64-cpython-38/lanedet/engine
copying lanedet/models/registry.py -> build/lib.linux-x86_64-cpython-38/lanedet/models
copying lanedet/models/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models
copying lanedet/ops/nms.py -> build/lib.linux-x86_64-cpython-38/lanedet/ops
copying lanedet/ops/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/ops
copying lanedet/utils/net_utils.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/registry.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/visualization.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/recorder.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/culane_metric.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/tusimple_metric.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/config.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/logger.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/utils/visualization_vid.py -> build/lib.linux-x86_64-cpython-38/lanedet/utils
copying lanedet/datasets/process/alaug.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/process.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/generate_lane_line.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/collect_lane.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/transforms.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/datasets/process/generate_lane_cls.py -> build/lib.linux-x86_64-cpython-38/lanedet/datasets/process
copying lanedet/models/heads/exist_head.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/plain_decoder.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/laneatt.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/lane_cls.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/condlane.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/busd.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/heads/lane_seg.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/heads
copying lanedet/models/necks/fpn.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/necks
copying lanedet/models/necks/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/necks
copying lanedet/models/backbones/erfnet.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/backbones
copying lanedet/models/backbones/mobilenet.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/backbones
copying lanedet/models/backbones/vgg.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/backbones
copying lanedet/models/backbones/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/backbones
copying lanedet/models/backbones/resnet.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/backbones
copying lanedet/models/aggregators/scnn.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/aggregators
copying lanedet/models/aggregators/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/aggregators
copying lanedet/models/aggregators/aspp.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/aggregators
copying lanedet/models/aggregators/transformer.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/aggregators
copying lanedet/models/aggregators/resa.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/aggregators
copying lanedet/models/nets/detector.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/nets
copying lanedet/models/nets/__init__.py -> build/lib.linux-x86_64-cpython-38/lanedet/models/nets
running egg_info
writing lanedet.egg-info/PKG-INFO
writing dependency_links to lanedet.egg-info/dependency_links.txt
writing requirements to lanedet.egg-info/requires.txt
writing top-level names to lanedet.egg-info/top_level.txt
reading manifest file 'lanedet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'lanedet.egg-info/SOURCES.txt'
running build_ext
building 'lanedet.ops.nms_impl' extension
Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    setup(
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 89, in run
    _build_ext.run(self)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 250, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 524, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/dell/anaconda3/envs/lanedet_v1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by FlyingDita** [comment]
it works when i use pip to pre-install requirement.txt.
maybe cause by the network.
