### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by oyoanan** [zillur-av/LVLane#15]
Hello, the dataset folder structure downloaded from the Tusimple official website includes train_set, test_set, test_label.json, and test_label.new.json. Is it necessary to merge train_set and test_set for dataset creation in your project execution document? Also, how do I use the test_label_classes.txt you provided? How is the dataset set when running training or testing commands? Looking forward to your reply, thank you!

**Comment by zillur01** [comment]
keep the test_label_classes.txt in the same directory as other json files and the run the segmentation mask creation script. it will generate new json file that includes both lane location and class id and use those for final training/inference. also, replace TuSimple test labels by my ones, they are mostly same except 2-3 changes.

instructions are provided in the readme file on how to run train/test. please let me know if you have any other questions.

**Comment by ZQEzekiel** [comment]
> Hello, the dataset folder structure downloaded from the Tusimple official website includes train_set, test_set, test_label.json, and test_label.new.json. Is it necessary to merge train_set and test_set for dataset creation in your project execution document? Also, how do I use the test_label_classes.txt you provided? How is the dataset set when running training or testing commands? Looking forward to your reply, thank you!

Hello, have you successfully set up the dataset? I encountered the following problem when using test_label_classes.txt to generate a new .JSON:
python tools/generate_seg_tusimple.py --root $DATASETROOT --filename 'test_label'
generating masks...
Traceback (most recent call last):
File "tools/generate_seg_tusimple.py", line 112, in <module>
generate_label(args)
File "tools/generate_seg_tusimple.py", line 102, in generate_label
gen_label_from_json(args.root, save_dir, file_name = args.filename)
File "tools/generate_seg_tusimple.py", line 84, in gen_label_from_json
cv2.imwrite(seg_path, seg_img)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'
Looking forward to your reply, thank you!
